# Generated by Django 3.2.7 on 2024-01-10 06:27

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=builtins.callable, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_Category', models.CharField(choices=[('salary', 'Salary/Wages'), ('freelance', 'Freelance/Consulting'), ('business', 'Business Income'), ('investment', 'Investment Returns'), ('gifts', 'Gifts/Donations'), ('side_hustles', 'Side Hustles'), ('rental', 'Rental Income'), ('interest', 'Interest and Dividends'), ('bonus', 'Bonus/Commisions'), ('other', 'Other')], max_length=20)),
                ('income_Description', models.TextField(blank=True)),
                ('income_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_Date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_details.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_Category', models.CharField(choices=[('housing', 'Housing'), ('childcare', 'Childcare'), ('transport', 'Transportation'), ('utlity', 'Utilities'), ('food', 'Food/Supplies'), ('pets', 'Pets'), ('savings', 'Savings'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('personal', 'Personal Care'), ('debt', 'Debt'), ('gifts', 'Gifts'), ('donations', 'Donantions'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=20)),
                ('expense_Description', models.TextField(blank=True)),
                ('expense_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_Date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_details.userdetails')),
            ],
        ),
    ]
