# Generated by Django 3.2.7 on 2024-01-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='user',
            new_name='user_info',
        ),
    ]
